Update db-backup.yml

diff --git a/.github/workflows/db-backup.yml b/.github/workflows/db-backup.yml
--- a/.github/workflows/db-backup.yml
+++ b/.github/workflows/db-backup.yml
@@ -8,8 +8,6 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-    - name: get timestamp
-      run: TIMESTAMP=$(date +"%Y-%m-%d %H:%M")" >> $GITHUB_ENV
     - name: take a backup from db
       uses: appleboy/ssh-action@v1.0.3
       with:
@@ -19,8 +17,8 @@ jobs:
         port: ${{ secrets.SSH_PORT }}
         script: |
           echo $TIMESTAMP
-          mysqldump -u ${{ secrets.DB_USER }} --database ${{ secrets.DB_NAME }} -p${{ secrets.DB_PASSWORD }} > db-backups/"$TIMESTAMP"-it_zeepup.sql
-          docker exec it_zeepup php artisan migrate || { echo "Migration failed, restoring database from backup..."; mysql -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} < db-backups/"$TIMESTAMP"-it_zeepup.sql; exit 1; }
+          mysqldump -u ${{ secrets.DB_USER }} --database ${{ secrets.DB_NAME }} -p${{ secrets.DB_PASSWORD }} > db-backups/$(date +"%Y-%m-%d)-it_zeepup.sql
+          docker exec it_zeepup php artisan migrate || { echo "Migration failed, restoring database from backup..."; mysql -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} < db-backups/$(date +"%Y-%m-%d)-it_zeepup.sql; exit 1; }
 
 
 
